---
services: docker

env:
  - distro: centos7
  - distro: fedora24
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: debian8

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Test whether supervisor is installed correctly.
  - docker exec --tty ${container_id} pip list installed | grep -e '^supervisor.*$'
  - docker exec --tty ${container_id} supervisorctl --help
  - docker exec --tty ${container_id} ps aux | grep supervisor

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
