---
- name: Ensure Supervisor is installed.
  pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version | default('latest') }}"

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    recurse: true
    mode: 0755

- include: config.yml

- include: init-setup.yml
  when: supervisor_started or supervisor_enabled

- name: Ensure Supervisor is started (if configured).
  service:
    name: supervisord
    state: started
  when: supervisor_started

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisord
    enabled: yes
  when: supervisor_enabled
